export const countryRegions = [
  {
    name: "Americas",
    countries: [
      { name: "United States", code: "US" },
      { name: "Canada", code: "CA" },
    ],
  },
  {
    name: "Europe",
    countries: [
      { name: "Austria", code: "AT" },
      { name: "Belgium", code: "BE" },
      { name: "Bulgaria", code: "BG" },
      { name: "Croatia", code: "HR" },
      { name: "Cyprus", code: "CY" },
      { name: "Czech Republic", code: "CZ" },
      { name: "Denmark", code: "DK" },
      { name: "Estonia", code: "EE" },
      { name: "Finland", code: "FI" },
      { name: "France", code: "FR" },
      { name: "Germany", code: "DE" },
      { name: "Greece", code: "GR" },
      { name: "Guernsey", code: "GG" },
      { name: "Hungary", code: "HU" },
      { name: "Ireland", code: "IE" },
      { name: "Italy", code: "IT" },
      { name: "Jersey", code: "JE" },
      { name: "Latvia", code: "LV" },
      { name: "Lithuania", code: "LT" },
      { name: "Luxembourg", code: "LU" },
      { name: "Malta", code: "MT" },
      { name: "Netherlands", code: "NL" },
      { name: "Norway", code: "NO" },
      { name: "Poland", code: "PL" },
      { name: "Portugal", code: "PT" },
      { name: "Romania", code: "RO" },
      { name: "Slovakia", code: "SK" },
      { name: "Slovenia", code: "SI" },
      { name: "Sweden", code: "SE" },
      { name: "Switzerland", code: "CH" },
      { name: "United Kingdom", code: "GB" },
    ],
  },
  {
    name: "Asia",
    countries: [
      { name: "Bahrain", code: "BH" },
      { name: "Hong Kong", code: "HK" },
      { name: "India", code: "IN" },
      { name: "Japan", code: "JP" },
      { name: "Kuwait", code: "KW" },
      { name: "Laos", code: "LA" },
      { name: "Oman", code: "OM" },
      { name: "Philippines", code: "PH" },
      { name: "Saudi Arabia", code: "SA" },
      { name: "Singapore", code: "SG" },
      { name: "Thailand", code: "TH" },
      { name: "United Arab Emirates", code: "AE" },
    ],
  },
  {
    name: "Oceania",
    countries: [
      { name: "Australia", code: "AU" },
      { name: "New Zealand", code: "NZ" },
    ],
  },
  {
    name: "Africa",
    countries: [
      { name: "Kenya", code: "KE" },
      { name: "Tanzania", code: "TZ" },
      { name: "Uganda", code: "UG" },
      { name: "Egypt", code: "EG" },
      { name: "Nigeria", code: "NG" },
    ],
  },
];
