import { Outfit, Poppins } from "next/font/google";
import "./globals.css";
import ClientWrapper from "./components/ClientWrapper";


const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["200"], // Multiple weights for better flexibility
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300"], // Multiple weights for better flexibility
});

export const metadata = {
  title: "Home Of Fragrances",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${poppins.variable} ${outfit.className} antialiased`}>
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
